from django.urls import path
from .views import get_all_admins, get_all_employees, get_all_faculties, get_all_instructors, get_departments_by_faculty, get_profile_data_api, login_api, register_employee_api, register_instructor_api
from api import views

urlpatterns = [
    path('login/', login_api, name='login_api'),
    path('register-instructor/', register_instructor_api, name='register_instructor'),
    path('register-employee/', views.register_employee_api, name='register_employee'),
    path('profile/<int:user_id>/', get_profile_data_api, name='get_profile'),
    path('faculties/', get_all_faculties, name='get_faculties'),
    path('faculties/<int:faculty_id>/departments/', get_departments_by_faculty, name='get_depts_by_faculty'),
    path('instructors/', get_all_instructors, name='all_instructors'),
    path('employees/', get_all_employees, name='all_employees'),
    path('admins/', get_all_admins, name='all_admins'),
    path('manage-instructor/<int:user_id>/', views.manage_instructor_api, name='manage_instructor'),
    path('manage-employee/<int:user_id>/', views.manage_employee_api, name='manage_employee'),
    path('courses/add/', views.add_course_api, name='add_course'),
    path('courses/', views.all_courses, name='all_courses'),
    path('courses/delete/<str:course_code>/', views.delete_course, name='delete_course'),
    path('courses/manage/<str:course_code>/', views.manage_course, name='manage_course'),
    path('courses/allocate/', views.allocate_course_api, name='allocate_course'),
    path('rooms/add/', views.add_room_api, name='add_room'),
    path('academic-years/open/', views.open_academic_year_api, name='open_academic_year_api'),
    path('semesters/open/', views.open_semester_api, name='open_semester_api'),
    path('semesters/update/<int:semester_id>/', views.update_semester_api, name='update_semester_api'),
    path('rooms/get/', views.get_rooms_api, name='get_rooms'),
    path('schedule/instructor/<int:instructor_id>/', views.get_instructor_daily_schedule, name='instructor_daily_schedule'),
    path('schedule/instructor/weekly/<int:instructor_id>/', views.get_instructor_weekly_schedule, name='instructor_weekly_schedule'),
    path('exams/assign-duties/', views.assign_exam_duties, name='assign_exam_duties'),
    path('check-attendance/', views.check_lecture_attendance, name='check_attendance'),
    path('check-exam-attendance/', views.check_exam_attendance, name='check_exam_attendance'),
    path('schedule_exams/instructor/<int:instructor_id>/', views.get_instructor_exam_duties, name='get_instructor_exam_duties'),
    path('academic-log/<int:user_id>/', views.academic_log_manager, name='academic_log_manager'),
    path('instructor-report/<int:user_id>/', views.get_instructor_teaching_load_report, name='instructor_report'),
    path('add-faculty/', views.add_faculty, name='add_faculty'),
    path('add-department/', views.add_department, name='add_department'),
    path('manage-room/<int:room_id>/', views.manage_room_api, name='manage_room'),
    path('instructors-for-employee/<int:employee_user_id>/', views.instructors_by_employee_faculty, name='instructors_for_employee'),
    path('courses-by-faculty/<int:faculty_id>/', views.courses_by_faculty, name='courses_by_faculty'),
    path('get/academic-years/', views.get_academic_years, name='get_academic_years'),
    path('confirm-load/<int:user_id>/', views.confirm_monthly_load, name='confirm_monthly_load'),
    path('get/available-years/', views.get_available_years, name='get_available_years'),
    path('get/instructors-monthly-status/', views.get_all_instructors_monthly_status, name='get_all_instructors_monthly_status'),
    path('send-reminder/', views.send_reminder_to_instructor, name='send_reminder_to_instructor'),
    path('user-notifications/<int:user_id>/', views.get_user_notifications, name='get_user_notifications'),
    path('user-notifications/<int:notification_id>/mark-as-read/', views.mark_notification_as_read, name='mark_notification_as_read'),
    path('add-compensatory-lecture/', views.add_compensatory_lecture, name='add_compensatory_lecture'),
    path('get/academic-holidays/', views.get_academic_holidays, name='get_academic_holidays'),
    path('get/lectures/', views.get_lectures, name='get_lectures'),
    path('manage-lectures/<int:lecture_id>/', views.manage_lecture_actions, name='manage_lecture_actions'),
    path('courses/hours-summary/', views.get_all_courses_hours_summary, name='get_all_courses_hours_summary'),
    path('instructor-projects/<int:instructor_id>/', views.get_instructor_projects, name='instructor_projects'),
    path('record-project-session/', views.record_project_session, name='record_project_session'),
    path('add-project/', views.add_project, name='add_project'),
    path('delete-project/<int:project_id>/', views.delete_project, name='delete_project'),
]