# Generated by Django 6.0.4 on 2026-04-09 13:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('academic_year_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('is_active', models.BooleanField()),
            ],
            options={
                'db_table': 'ACADEMIC_YEAR',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(db_collation='Arabic_CI_AS', max_length=50, primary_key=True, serialize=False)),
                ('course_name', models.CharField(db_collation='Arabic_CI_AS', max_length=255)),
                ('credit_hours', models.IntegerField(default=3)),
            ],
            options={
                'db_table': 'COURSE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='Arabic_CI_AS', max_length=255)),
            ],
            options={
                'db_table': 'FACULTY',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(db_collation='Arabic_CI_AS', max_length=100)),
                ('capacity', models.IntegerField(default=40)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ROOM',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(db_collation='Arabic_CI_AS', max_length=15, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'USERS',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ADMIN',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.faculty')),
            ],
            options={
                'db_table': 'EMPLOYEE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='Arabic_CI_AS', max_length=255)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.faculty')),
            ],
            options={
                'db_table': 'DEPARTMENT',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructor_id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_rank', models.CharField(db_collation='Arabic_CI_AS', max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'INSTRUCTOR',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CourseAllocation',
            fields=[
                ('course_allocation_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.ForeignKey(db_column='course_code', on_delete=django.db.models.deletion.DO_NOTHING, to='api.course')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.employee')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.instructor')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.room')),
            ],
            options={
                'db_table': 'COURSE_ALLOCATION',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(db_collation='Arabic_CI_AS', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PROFILE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lectures',
            fields=[
                ('lecture_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(db_collation='Arabic_CI_AS', max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('lecture_type', models.CharField(db_collation='Arabic_CI_AS', max_length=50)),
                ('course_allocation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.courseallocation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.room')),
            ],
            options={
                'db_table': 'LECTURES',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester_name', models.CharField(db_collation='Arabic_CI_AS', max_length=100)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.academicyear')),
            ],
            options={
                'db_table': 'SEMESTER',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='courseallocation',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.semester'),
        ),
        migrations.CreateModel(
            name='TeachingLoad',
            fields=[
                ('teaching_load_id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance', models.BooleanField()),
                ('lecture_date', models.DateField()),
                ('course_allocation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.courseallocation')),
            ],
            options={
                'db_table': 'TEACHING_LOAD',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExamDuty',
            fields=[
                ('exam_duty_id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.employee')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.room')),
                ('teaching_load', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.teachingload')),
            ],
            options={
                'db_table': 'EXAM_DUTY',
                'managed': True,
            },
        ),
    ]
