# Generated by Django 6.0.4 on 2026-04-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('instructor', 'Instructor'), ('employee', 'Employee')], default='admin', max_length=20),
        ),
        migrations.AlterModelTable(
            name='user',
            table='USER',
        ),
    ]
