# Generated by Django 6.0.4 on 2026-04-10 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_instructor_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.faculty'),
        ),
    ]
