# Generated by Django 6.0.4 on 2026-04-10 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseallocation',
            name='employee',
        ),
    ]
