# Generated by Django 6.0.4 on 2026-04-10 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_courseallocation_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examduty',
            name='employee',
        ),
        migrations.AddField(
            model_name='examduty',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.instructor'),
        ),
    ]
