# Generated by Django 6.0.4 on 2026-04-10 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_examduty_employee_examduty_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examduty',
            name='teaching_load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.teachingload'),
        ),
    ]
