# Generated by Django 6.0.4 on 2026-04-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_examduty_teaching_load'),
    ]

    operations = [
        migrations.AddField(
            model_name='examduty',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examduty',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
