# Generated by Django 6.0.4 on 2026-04-15 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_examduty_end_time_examduty_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.department'),
            preserve_default=False,
        ),
    ]
