# Generated by Django 6.0.4 on 2026-04-19 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_course_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicHoliday',
            fields=[
                ('holiday_id', models.AutoField(primary_key=True, serialize=False)),
                ('holiday_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='api.academicyear')),
            ],
            options={
                'db_table': 'ACADEMIC_HOLIDAYS',
                'managed': True,
                'unique_together': {('academic_year', 'holiday_date')},
            },
        ),
    ]
