# Generated by Django 6.0.4 on 2026-04-19 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_academicholiday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicholiday',
            options={},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={},
        ),
        migrations.RenameField(
            model_name='semester',
            old_name='date_end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='semester',
            old_name='date_start',
            new_name='start_date',
        ),
        migrations.AlterUniqueTogether(
            name='academicholiday',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='academicholiday',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.semester'),
        ),
        migrations.AddField(
            model_name='semester',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.academicyear'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='academicholiday',
            table=None,
        ),
        migrations.AlterModelTable(
            name='semester',
            table='ACADEMIC_SEMESTER',
        ),
        migrations.RemoveField(
            model_name='academicholiday',
            name='academic_year',
        ),
    ]
