# Generated by Django 6.0.4 on 2026-04-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_academicholiday_options_alter_semester_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='coordination_start_date',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
    ]
