# Generated by Django 6.0.4 on 2026-05-10 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_semester_coordination_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='examduty',
            name='course_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.course'),
        ),
    ]
