# Generated by Django 6.0.2 on 2026-05-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_examduty_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingload',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
