# Generated by Django 6.0.4 on 2026-05-19 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_teachingload_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='examduty',
            name='exam_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examduty',
            name='exam_name',
            field=models.CharField(default='امتحان', max_length=100),
        ),
        migrations.AlterField(
            model_name='examduty',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.room'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('REMINDER', 'تذكير'), ('INFO', 'معلومة'), ('WARNING', 'تنبيه')], default='INFO', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'NOTIFICATION',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
