# Generated by Django 6.0.4 on 2026-05-19 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_examduty_exam_end_date_examduty_exam_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingload',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachingload',
            name='is_compensatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teachingload',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.room'),
        ),
        migrations.AddField(
            model_name='teachingload',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
