# Generated by Django 6.0.4 on 2026-05-20 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_teachingload_end_time_teachingload_is_compensatory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduationProject',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_title', models.CharField(db_collation='Arabic_CI_AS', max_length=255)),
                ('project_type', models.CharField(choices=[('term_project', 'فصلي'), ('grad_1', 'تخرج 1'), ('grad_2', 'تخرج 2')], default='grad_1', max_length=20)),
                ('student_names', models.TextField(db_collation='Arabic_CI_AS', help_text='أسماء الطلاب المشاركين')),
                ('theory_hours', models.FloatField(default=0.0)),
                ('practical_hours', models.FloatField(default=0.0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.faculty')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='supervised_projects', to='api.instructor')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.semester')),
            ],
            options={
                'db_table': 'GRADUATION_PROJECT',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProjectSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.graduationproject')),
                ('teaching_load', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_sessions', to='api.teachingload')),
            ],
            options={
                'db_table': 'PROJECT_SESSION',
                'managed': True,
            },
        ),
    ]
