# Generated by Django 6.0.4 on 2026-05-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_graduationproject_projectsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduationproject',
            name='assigned_day',
            field=models.IntegerField(blank=True, choices=[(1, 'الإثنين'), (2, 'الثلاثاء'), (3, 'الأربعاء'), (4, 'الخميس'), (5, 'الجمعة'), (6, 'السبت'), (7, 'الأحد')], help_text='اليوم المعتمد للمتابعة خلال الأسبوع', null=True),
        ),
        migrations.AddField(
            model_name='graduationproject',
            name='end_time',
            field=models.TimeField(blank=True, help_text='وقت انتهاء المتابعة المعتمد', null=True),
        ),
        migrations.AddField(
            model_name='graduationproject',
            name='start_time',
            field=models.TimeField(blank=True, help_text='وقت بدء المتابعة المعتمد', null=True),
        ),
    ]
